export const SET_FORMS = "SET_FORMS";
export const SET_FORM = "SET_FORM";
export const RESET_FORMS = "RESET_FORMS";
export const RESET_FORMS_LOADING = "RESET_FORMS_LOADING";
export const SET_FORMS_HAVE_MORE = "SET_FORMS_HAVE_MORE";
export const GO_TO_NEXT_PAGE = "GO_TO_NEXT_PAGE";
export const GO_TO_PREVIOUS_PAGE = "GO_TO_PREVIOUS_PAGE";
export const SET_FORMS_LOADING = "SET_FORMS_LOADING";
